tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazygit"
tap "mongodb/brew"
brew "python@3.8", link: true
brew "awscli"
brew "cmake"
brew "coreutils"
brew "docker", link: false
brew "fzf"
brew "git"
brew "go"
brew "jq"
brew "libpq"
brew "macvim"
brew "mdp"
brew "mono"
brew "neovim", args: ["HEAD"]
brew "node"
brew "postgresql"
brew "redis"
brew "ripgrep"
brew "thefuck"
brew "tig"
brew "tmux"
brew "tree"
brew "wget"
brew "xsv"
brew "jesseduffield/lazygit/lazygit"
brew "mongodb/brew/mongocli"
brew "mongodb/brew/mongodb-community"
cask "graphql-playground"
